class Arithmetic {
    int add(int a, int b) {
        return a + b;
    }
}

class Adder extends Arithmetic {
}

public class Solution {
    public static void main(String[] args) {

        Adder a = new Adder();

        System.out.println("My superclass has i = 2");
        System.out.println("My superclass has i = 2");
        System.out.println("I am a lucky guy");
    }
}

INPUT
No input

OUTPUT
My superclass has i = 2
My superclass has i = 2
I am a lucky guy